substitutions:
  name: round_upper
  friendly_name: round_upper

  min_thermostat_temp: 13.0
  max_thermostat_temp: 30.0

  default_brightness: 0.29  # conservative brightness

esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  min_version: 2024.11.0
  name_add_mac_suffix: false
  platformio_options:
    board_build.flash_mode: dio
    board_build.arduino.memory_type: qio_opi
    build_flags: "-DBOARD_HAS_PSRAM"
    board_upload.maximum_ram_size: 524288

  on_boot:
    priority: -100
    then:
#      - delay: 1s
      - lambda: |-
          uint32_t c = id(ui_color1_hex);
          uint8_t r = (c >> 16) & 0xFF;
          uint8_t g = (c >> 8) & 0xFF;
          uint8_t b = c & 0xFF;
          id(ui_color1) = lv_color_make(r, g, b);
      - lambda: |-
          uint32_t c = id(ui_color2_hex);
          uint8_t r = (c >> 16) & 0xFF;
          uint8_t g = (c >> 8) & 0xFF;
          uint8_t b = c & 0xFF;
          id(ui_color2) = lv_color_make(r, g, b);
      - script.execute: apply_ui_color
      - script.execute: update_needle_and_arc




esp32:
  board: esp32-s3-devkitc-1
  flash_size: 16MB
  framework:
    type: esp-idf
    version: recommended
    sdkconfig_options:
      CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240: y
      CONFIG_ESP32S3_DATA_CACHE_64KB: y
      CONFIG_SPIRAM_FETCH_INSTRUCTIONS: y
      CONFIG_SPIRAM_RODATA: y

psram:
  speed: 80MHz
  mode: octal

logger:
  level: DEBUG

debug:
  update_interval: 30s

# Enable Home Assistant API
api:
  encryption:
    key: "G8g/K7DFePCkQtmOJEJJ0/Ex68wkwgAaoDa+J4MDg0U="

ota:
  - platform: esphome
    password: "510ddea871797acef40908cdab6e6f27"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Round-Upper Fallback Hotspot"
    password: "8dx7BTuAN3Uh"

preferences:
  flash_write_interval: 30s



mdns:
  disabled: false

<<: !include includes/_round_128b.yaml

spi:
  id: spi_bus
  mosi_pin: GPIO13
  clk_pin: GPIO14

i2c:
  - id: i2c_bus
    sda: 17
    scl: 18
    scan: true
    frequency: 400kHz
  - id: i2c_touch
    sda: 38
    scl: 39
    scan: true
    frequency: 400kHz

touchscreen:
  platform: cst816
  id: touch
  interrupt_pin: GPIO40
  reset_pin: GPIO16
  i2c_id: i2c_touch
  transform:
    mirror_x: false
    mirror_y: true
    swap_xy: true
  on_release:
    then:
      - if:
          condition: lvgl.is_paused
          then:
            - logger.log: "LVGL resuming"
            - lvgl.resume
            - lvgl.widget.redraw
            - light.turn_on: display_backlight

light:
  - platform: monochromatic
    id: display_backlight
    name: "Backlight"
    output: backlight_output
    default_transition_length:
      milliseconds: 0
    initial_state:
      brightness: 100%
    restore_mode: ALWAYS_ON



  - platform: rgb
    name: "UI Accent Color1"
    id: ui_color1_light
    red: output_dummy_r
    green: output_dummy_g
    blue: output_dummy_b
    default_transition_length: 0s
    restore_mode: RESTORE_DEFAULT_ON

    on_state:
      then:
        - lambda: |-
            float br = id(ui_color1_light).current_values.get_brightness();
            uint8_t r = (uint8_t)(id(ui_color1_light).current_values.get_red() * br * 255.0f);
            uint8_t g = (uint8_t)(id(ui_color1_light).current_values.get_green() * br * 255.0f);
            uint8_t b = (uint8_t)(id(ui_color1_light).current_values.get_blue() * br * 255.0f);
            id(ui_color1_hex) = ((uint32_t)r << 16) | ((uint32_t)g << 8) | (uint32_t)b;
            id(ui_color1) = lv_color_make(r, g, b);

        - script.execute: apply_ui_color
        - script.execute: refresh_page


  - platform: rgb
    name: "UI Accent Color2"
    id: ui_color2_light
    red: output_dummy_r
    green: output_dummy_g
    blue: output_dummy_b
    default_transition_length: 0s
    restore_mode: RESTORE_DEFAULT_ON

    on_state:
      then:
        - lambda: |-
            float br = id(ui_color2_light).current_values.get_brightness();
            uint8_t r = (uint8_t)(id(ui_color2_light).current_values.get_red() * br * 255.0f);
            uint8_t g = (uint8_t)(id(ui_color2_light).current_values.get_green() * br * 255.0f);
            uint8_t b = (uint8_t)(id(ui_color2_light).current_values.get_blue() * br * 255.0f);

            id(ui_color2_hex) = ((uint32_t)r << 16) | ((uint32_t)g << 8) | (uint32_t)b;
            id(ui_color2) = lv_color_make(r, g, b);

        - script.execute: apply_ui_color
        - script.execute: refresh_page


number:
  - platform: template
    name: LVGL Screen timeout
    optimistic: true
    id: display_timeout
    unit_of_measurement: "s"
    initial_value: 45
    restore_value: true
    min_value: 10
    max_value: 180
    step: 5
    mode: box


globals:
  - id: ui_color1_hex
    type: uint32_t
    restore_value: true
    initial_value: '0x0CFF06'   # startkleur

  - id: ui_color2_hex
    type: uint32_t
    restore_value: true
    initial_value: '0x0CFF06'   # startkleur


  - id: ui_color1
    type: lv_color_t
    initial_value: 'lv_color_hex(0x0CFF06)'

  - id: ui_color2
    type: lv_color_t
    initial_value: 'lv_color_hex(0x0CFF06)'




sensor:
  - platform: homeassistant
    id: current_temp
    entity_id: climate.verwarming
#    entity_id: climate.climate_control
    attribute: current_temperature
    on_value:
      then:
        - script.execute: update_needle_and_arc
        - light.turn_on: display_backlight
        - lvgl.resume
        - lvgl.widget.redraw

  - platform: homeassistant
    id: target_temp
    entity_id: climate.verwarming
    attribute: temperature
    on_value:
      then:
        - script.execute: update_needle_and_arc

  - platform: rotary_encoder
    id: encoder
    pin_a: GPIO9
    pin_b: GPIO10
    on_clockwise:
      then:
        - logger.log: "Rotary Clockwise"
        - script.execute:
            id: increment_temperature
            delta: 0.5
        - lvgl.resume
        - lvgl.widget.redraw
        - light.turn_on: display_backlight
    on_anticlockwise:
      then:
        - logger.log: "Rotary Anti Clockwise"
        - script.execute:
            id: increment_temperature
            delta: -0.5
        - lvgl.resume
        - lvgl.widget.redraw
        - light.turn_on: display_backlight

output:
  - platform: ledc
    pin: GPIO7
    id: backlight_output


  - platform: template
    id: output_dummy_r
    type: float
    write_action:
      - lambda: |-
          // Do nothing, just required for RGB light

  - platform: template
    id: output_dummy_g
    type: float
    write_action:
      - lambda: |-
          // Do nothing

  - platform: template
    id: output_dummy_b
    type: float
    write_action:
      - lambda: |-
          // Do nothing



time:
  - platform: homeassistant
    id: homeassistant_time
    timezone: Europe/Berlin

switch:
  - platform: template
    id: screensaver_enabled
    name: "Screensaver enabled"
    optimistic: true

  - platform: template
    name: Antiburn
    id: switch_antiburn
    icon: mdi:television-shimmer
    optimistic: true
    entity_category: "config"
    turn_on_action:
      - logger.log: "Starting Antiburn"
      - if:
          condition: lvgl.is_paused
          then:
            - lvgl.resume
            - lvgl.widget.redraw
      - lvgl.pause:
          show_snow: true
    turn_off_action:
      - logger.log: "Stopping Antiburn"
      - if:
          condition: lvgl.is_paused
          then:
            - lvgl.resume
            - lvgl.widget.redraw


binary_sensor:
  - platform: gpio
    name: Button
    id: front_button
    pin: 
      number: GPIO6
      inverted: True
    on_press:
      then:
        - lambda: |-
            float current = id(target_temp).state;
            float next;

            if (current <= 17.0) {
              next = 20.0;
            } else {
              next = 17.0;
            }

            id(target_temp).publish_state(next);
        - homeassistant.service:
            service: climate.set_temperature
            data:
              entity_id: climate.verwarming
              temperature: !lambda "return id(target_temp).state;"
        - script.execute: update_needle_and_arc
        - lvgl.resume
        - lvgl.widget.redraw
        - light.turn_on: display_backlight



display:
  - platform: ili9xxx
    id: round_display
    model: GC9A01A
    cs_pin: GPIO15
    reset_pin: GPIO11
    dc_pin: GPIO21
    invert_colors: true
    auto_clear_enabled: false
    color_order: bgr
    rotation: 180

lvgl:
  on_idle:
    timeout: !lambda "return id(display_timeout).state * 1000;"
    then:
      - if:
          condition:
            switch.is_on: screensaver_enabled
          then:
            - light.turn_off: display_backlight
            - lvgl.pause: {}

  bg_color: black
  scrollbar_mode: "OFF"
  default_font: roboto_med
  text_color: white
  style_definitions:
    - id: style_menu_button
      align: CENTER
      bg_opa: TRANSP
      shadow_opa: TRANSP
      height: 50
      width: 50
      radius: 50%
    - id: style_menu_button_label
      align: CENTER
      y: 3
      text_font: roboto_med

    - id: arc_bg
      bg_opa: TRANSP
      arc_color: 0x2A2A2A     # inactieve ring
      arc_width: 24
      arc_rounded: true

    - id: arc_indicator_heat
      arc_color: 0xFF8C1A     # Nest-oranje
      arc_width: 24
      arc_rounded: true

    - id: center_text
      text_color: 0xEDEDED
      text_font: montserrat_48

  pages:
    - id: main_page
      on_load:
#        - globals.set:
#            id: active_lvgl_page
#            value: 'main_page'
        - script.execute: apply_ui_color

      on_unload:
        - lvgl.widget.disable: []

      widgets:
        - arc:
                id: setpoint_arc
                align: CENTER
                width: 240
                height: 240
                adjustable: false

                # schaal in 0.1°C
                min_value: 150
                max_value: 300
                value: 205         # start op 20.5°C

                # Nest-achtige "open" ring (gap onder)
                start_angle: 135
                end_angle: 45
                rotation: 0
                arc_width: 24
                change_rate: 720   # default uit ESPHome docs

                # Stijl van de waarde-indicator (het "gevulde" deel)
                indicator:
                  arc_width: 24
                  arc_color: !lambda return id(ui_color2);
  
               
        - obj:
            id: mode_bg
            height: 140
            width: 140
            radius: 70
            align: CENTER
            border_width: 0
            bg_color: black
        - label:
            id: meas_temp_label
            align: CENTER
            y: +18
            text_color: white
            text_font: roboto_huge
            text: "--.-"
        - label:
            id: celsius_label
            align: CENTER
            x: 70
            y: -3
            text_font: roboto_med
            text: "°C"
        - label:
            id: set_temp_label
            align: CENTER
            text_color: white
            y: +80
            text_font: roboto_large
            text: "--.-"
        - label:
            id: mode_label
            align: CENTER
            y: -56
            text_font: roboto_med
            text: "CV"

script:


  - id: update_needle_and_arc
    then:
      - script.execute: _update_needle_and_arc

  - id: _update_needle_and_arc
    then:
      - lambda: |-
          if (isnan(id(target_temp).state) || isnan(id(current_temp).state)) {
            ESP_LOGW("UI", "Climate data unavailable");
            return;
          }
          ESP_LOGW("UI", "Climate n and a");


      - lvgl.arc.update:
          id: setpoint_arc
          value: !lambda return id(target_temp).state * 10.0;
          arc_color: !lambda return id(ui_color1);



      - lvgl.label.update:
          id: set_temp_label
          text: !lambda |-
            if (id(target_temp).state <= 17.0) {
              ESP_LOGW("UI", "Return off");
              return "OFF";
            }
            static char buffer[8];
            ESP_LOGW("UI", "Return value");
            sprintf(buffer, "%.1f", id(target_temp).state);
            return buffer;
      - lvgl.label.update:
          id: meas_temp_label
          text: !lambda |-
            char buffer[8];
            sprintf(buffer, "%.1f", id(current_temp).state);
            return buffer;

  - id: refresh_page
    then:
      - lvgl.page.show:
          id: main_page
          animation: NONE
          time: 0ms


  - id: increment_temperature
    parameters:
      delta: float
    then:
      - lambda: |-
          float current;
          current = id(target_temp).state;
          float next = current + delta;

          // begrenzen
          if (next < ${min_thermostat_temp}) next = ${min_thermostat_temp};
          if (next > ${max_thermostat_temp}) next = ${max_thermostat_temp};

          id(target_temp).publish_state(next);

      - homeassistant.service:
          service: climate.set_temperature
          data:
            entity_id: climate.verwarming
            temperature: !lambda "return id(target_temp).state;"



  - id: apply_ui_color
    then:
      - lvgl.arc.update:
          id: setpoint_arc
          arc_color: !lambda |-
            return id(ui_color1);
          indicator:
            arc_color: !lambda |-
              return id(ui_color2);
            arc_width: 24
            arc_rounded: true

      # (optioneel) als je inner_ring ook wil laten meekleuren:
      # - lvgl.arc.update:
      #     id: inner_ring
      #     arc_color: !lambda return id(ui_color);

      - lvgl.widget.redraw


